"""empty message

Revision ID: 572d531352d1
Revises: 
Create Date: 2023-10-10 20:39:35.052098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '572d531352d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=4096), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    # ### end Alembic commands ###
