"""empty message

Revision ID: 768d0e72a972
Revises: 572d531352d1
Create Date: 2023-10-10 21:12:16.143547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '768d0e72a972'
down_revision = '572d531352d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posted', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('posted')

    # ### end Alembic commands ###
